// Generated by CoffeeScript 1.8.0
describe("ProtoSimple", function() {
  beforeEach(function() {
    this.Animal = BasicObject.extend("Animal", {
      legs: 2
    });
    this.animal = this.Animal.create();
    this.animal2 = this.Animal.create();
    this.Dog = this.Animal.extend("Dog", {
      initialize: function(name) {
        return this.name = name;
      },
      legs: 4
    });
    return this.dog = this.Dog.create("Ogden");
  });
  it("outputs to console", function() {
    if ((typeof console !== "undefined" && console !== null) && (console.dir != null)) {
      console.dir(this.dog);
    }
    return expect(true).toBe(true);
  });
  it("inherits non-overridden properties", function() {
    return expect(this.animal.legs).toBe(2);
  });
  it("does not override other sibling type properties", function() {
    this.animal.legs = 6;
    return expect(this.animal2.legs).toBe(2);
  });
  it("overrides properties when extending", function() {
    return expect(this.dog.legs).toBe(4);
  });
  return it("runs initialize() on creation", function() {
    return expect(this.dog.name).toBe("Ogden");
  });
});

//# sourceMappingURL=test_protosimple.js.map
